apis/urls.py
from django.urls import path, include
from . import api

app_name = 'api'
urlpatterns = [
    path('products/', api.ProductView.as_view(), name='product-list'),
    path('users/', api.UserView.as_view(), name='users-list'),
    path('carts/', api.CartView.as_view(), name='carts-list'),
    path('checkouts/', api.CheckoutView.as_view(), name='checkouts-list'),
    path('orders/', api.OrderView.as_view(), name='orders-list'),
]

payment/urls.py
from .views import checkout_view
from .api import create_payment, payment_callback
from django.urls import path

app_name= "payment"
urlpatterns = [
    path('', checkout_view, name='checkout'),
    path("paymob/create/", create_payment, name='paymob'),
    path("paymob/webhook/", payment_callback),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<int:pk>/', views.product_details, name='product-details'),
    path('cart/', views.cart, name='cart'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('checkout/', include('payment.urls')),
    path('api/', include('apis.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
from users.models import CustomUser

# Create your models here.

checkout_country_choices = [
    ('USA', 'United States'),
    ('MEX', 'Mexico'),
    ('EGY', 'Egypt'),
    ('CAN', 'Canada'),
    ('UK', 'United Kingdom'),
    ('AUS', 'Australia'),
    ('IND', 'India'),
    ('GER', 'Germany'),
    ('FRA', 'France'),
    ('JPN', 'Japan'),
    ('CHN', 'China'),
    ('BRA', 'Brazil'),
]


class checkout(models.Model):
    checkout_firstname = models.CharField(max_length=30)
    checkout_lastname = models.CharField(max_length=3)
    checkout_company_name = models.CharField(max_length=100, blank=True, null=True)
    checkout_email = models.EmailField()
    checkout_country = models.CharField(max_length=50, choices=checkout_country_choices)
    checkout_town = models.CharField(max_length=255)
    checkout_address = models.CharField(max_length=255)
    checkout_zipcode = models.CharField(max_length=20)
    checkout_phone_number = models.CharField(max_length=20)
    checkout_order_comment = models.TextField(blank=True, null=True)
    checkout_create_account = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Checkout of {self.checkout_firstname} {self.checkout_lastname} at {self.created_at}"
    
class order(models.Model):
    order_checkout = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    paymob_order_id= models.CharField(max_length=50, null=True, blank=True)
    order_total_price = models.DecimalField(max_digits=10, decimal_places=2)
    order_status = models.CharField(max_length=50, default='Pending')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order #{self.id} - {self.order_status}"

payment/forms.py
from django import forms
from .models import checkout, checkout_country_choices

class CheckoutForm(forms.ModelForm):
    checkout_firstname = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'form-control', 'id': 'first_name'}))
    checkout_lastname = forms.CharField(max_length=30, required=True, widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'form-control', 'id': 'last_name'}))
    checkout_company_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'placeholder': 'Company Name', 'class': 'form-control', 'id': 'company'}))
    checkout_email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'placeholder': 'Email', 'class': 'form-control', 'id': 'email'}))
    checkout_country = forms.ChoiceField(choices=checkout_country_choices, required=True, widget=forms.Select(attrs={'class': 'w-100', 'id': 'country'}))
    checkout_town = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'placeholder': 'Town', 'class': 'form-control', 'id': 'city'}))
    checkout_address = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'placeholder': 'Address', 'class': 'form-control mb-3', 'id': 'street_address'}))
    checkout_zipcode = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'Zip Code', 'class': 'form-control', 'id': 'zip_code'}))
    checkout_phone_number = forms.CharField(max_length=20, required=True, widget=forms.TextInput(attrs={'placeholder': 'Phone No', 'class': 'form-control', 'id': 'phone_number', 'min': '0'}))
    checkout_order_comment = forms.CharField(required=False, widget=forms.Textarea(attrs={'placeholder': 'Leave a comment about your order', 'class': 'form-control w-100', 'id': 'comment', 'cols': '30', 'rows': '10', 'name': 'comment'}))
    checkout_create_account = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'id': 'customCheck2', 'class': 'custom-control-input', 'label': 'Create an account?', 'for': 'customCheck2'}))    
    
    class Meta:
        model = checkout
        fields = [
            'checkout_firstname',
            'checkout_lastname',
            'checkout_company_name',
            'checkout_email',
            'checkout_country',
            'checkout_town',
            'checkout_address',
            'checkout_zipcode',
            'checkout_phone_number',
            'checkout_order_comment',
            'checkout_create_account',
        ]

payment/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from products.models import Cart
from .models import order
from .forms import CheckoutForm
from users.models import CustomUser as User
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import logout
from django.core.mail import send_mail
from django.conf import settings
# Create your views here.

@login_required
@csrf_exempt
def checkout_view(request):
    cart_items = Cart.objects.filter(cart_user=request.user)
    last_login = request.user.last_login
    user_order = order.objects.filter(
        order_checkout=request.user,
        created_at__gte=request.user.last_login
    ).order_by('-created_at').first()

    # Calculate subtotal and total price
    sub_price = 0
    total_price = 0
    for item in cart_items:
        sub_price+= item.cart_sub_price
        total_price+= item.cart_total_price
        
    # Handle form submission
    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['checkout_create_account'] == True:
                User.objects.get_or_create(
                    first_name=form.cleaned_data['checkout_firstname'],
                    last_name=form.cleaned_data['checkout_lastname'],
                    email=form.cleaned_data['checkout_email'],
                    phone_number=form.cleaned_data['checkout_phone_number'],
                    address=form.cleaned_data['checkout_address'],
                    payment_method='Cash',
                    password='defaultpassword'
                )
                
            form.save()
    else:
        form = CheckoutForm()
    
    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('users:login')
    
    
    # Isn't allowed on Railway
    
#     if request.method == 'POST' and 'email_subscription' in request.POST:
#         email= request.POST.get('email_subscription')
#         Subscribtions.objects.create(
#             subscribtion_user= request.user,
#             subscribtions_email= email,
#         )
        
#         message=f"""Hi {request.user.first_name},

# Subscription confirmed — welcome to the community!
#         """
#         send_mail(
#             "Furniture Payment",
#             message,
#             settings.EMAIL_HOST_USER,
#             [request.user.email],
#             fail_silently=False,
#         )
    
    context={
        'sub_price': sub_price,
        'total_price': total_price,
        'cart_items': cart_items,
        'form': CheckoutForm,
        'user_order': user_order,
    }
    return render(request, 'payment/checkout.html', context)

payment/templates/payment/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo" style="margin-bottom: 80px !important;">
                <a href="{% url 'products:home' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
            </div>

            <div class="user-greeting d-flex align-items-center gap-2" style="font-size:14px; color: #fbb710; margin-bottom: 20px;">
            <span>Hi, {{ request.user.first_name }}!</span>
            <form method="POST" action="" style="margin-left: auto;">
                {% csrf_token %}
                <button type="submit" class="btn-logout-icon" name="logout" style="
                background:none;
                border:none;
                color:#fbb710;
                font-size:16px;
                cursor:pointer;
                transition:0.3s;
            " title="Logout">
                <i class="fa fa-sign-out" aria-hidden="true"></i>
            </button>
            </form>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li><a href="{% url 'products:home' %}">Home</a></li>
                    <li><a href="{% url 'products:shop' %}">Shop</a></li>
                    <li><a href="{% url 'products:cart' %}">Cart</a></li>
                    <li class="active"><a href="{% url 'payment:checkout' %}">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">

            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="{% url 'products:cart' %}" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> Cart <span>({{ cart_items.count|default:0 }})</span></a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->

        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="checkout_details_area mt-50 clearfix">

                            <div class="cart-title">
                                <h2>Checkout</h2>
                            </div>
                            {% if user_order %}
                            {% if user_order.order_status == "success" %}
                                <div class="alert-messages mb-3">
                                        <div class="alert alert-success">Payment successful!</div>
                                </div>
                            {% else %}
                                <div class="alert-messages mb-3">
                                        <div class="alert alert-danger">Payment failed!</div>
                                </div>
                            {% endif %}
                            {% endif %}
                            <form action="#" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        {{ form.checkout_firstname }}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        {{ form.checkout_lastname }}
                                    </div>
                                    <div class="col-12 mb-3">
                                        {{ form.checkout_company_name }}
                                    </div>
                                    <div class="col-12 mb-3">
                                        {{ form.checkout_email }}
                                    </div>
                                    <div class="col-12 mb-3">
                                        {{ form.checkout_country }}
                                    </div>
                                    <div class="col-12 mb-3">
                                        {{ form.checkout_address }}
                                    </div>
                                    <div class="col-12 mb-3">
                                        {{ form.checkout_town }}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        {{ form.checkout_zipcode }}
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        {{ form.checkout_phone_number }}
                                    </div>
                                    <div class="col-12 mb-3">
                                        {{ form.checkout_order_comment }}
                                    </div>

                                    <div class="col-12">
                                        <div class="custom-control custom-checkbox d-block mb-2">
                                            {{ form.checkout_create_account }}
                                            <label class="custom-control-label" for="customCheck2">Create an accout</label>
                                        </div>
                                        
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Cart Total</h5>
                            <ul class="summary-table">
                                <li><span>subtotal:</span> <span>${{sub_price}}</span></li>
                                <li><span>delivery:</span> <span>$50</span></li>
                                <li><span>total:</span> <span>${{total_price}}</span></li>
                            </ul>
                            <form action="{% url 'payment:paymob' %}" method="post" id="paymob-form">
                            {% csrf_token %}
                            <div class="payment-method">
                                <!-- Cash on delivery -->
                                <div class="custom-control custom-checkbox mr-sm-2">
                                    <input type="checkbox" class="custom-control-input" id="cod" checked>
                                    <label class="custom-control-label" for="cod">Cash on Delivery</label>
                                </div>
                                <!-- paymob -->
                                or
                                <div class="custom-control custom-checkbox mr-sm-2">
                                    <a href="#" onclick="document.getElementById('paymob-form').submit();" style="font-size: 14px;
                                            color: #6b6b6b;
                                            font-weight: 400;
                                            margin-bottom: 15px;">
                                    Choose paymob<img class="ml-15" src="{% static 'img/core-img/paypal.png' %}" alt="">
                                    </a>
                                </div>
                            </div>

                            <div class="cart-btn mt-100">
                                <input type="submit" class="btn amado-btn w-100" value="Checkout">
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->
{% endblock %}