apis/urls.py
from django.urls import path, include
from . import api

app_name = 'api'
urlpatterns = [
    path('products/', api.ProductView.as_view(), name='product-list'),
    path('users/', api.UserView.as_view(), name='users-list'),
    path('carts/', api.CartView.as_view(), name='carts-list'),
    path('checkouts/', api.CheckoutView.as_view(), name='checkouts-list'),
    path('orders/', api.OrderView.as_view(), name='orders-list'),
]

payment/urls.py
from .views import checkout_view
from .api import create_payment, payment_callback
from django.urls import path

app_name= "payment"
urlpatterns = [
    path('', checkout_view, name='checkout'),
    path("paymob/create/", create_payment, name='paymob'),
    path("paymob/webhook/", payment_callback),
]

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'
urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<int:pk>/', views.product_details, name='product-details'),
    path('cart/', views.cart, name='cart'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('checkout/', include('payment.urls')),
    path('api/', include('apis.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.forms import ValidationError
from django.conf import settings
from users.models import CustomUser
from cloudinary.models import CloudinaryField
from django_resized import ResizedImageField
# Create your models here.


prod_brand= [
    ('Ikea', 'Ikea'),
    ('Amado', 'Amado'),
    ('Furniture Inc', 'Furniture Inc'),
    ('The factory', 'The factory'),
    ('Artdeco', 'Artdeco'),
]


prod_cat=[
    ('Chairs', 'Chairs'),
    ('Beds', 'Beds'),
    ('Accessories', 'Accessories'),
    ('Furnitures', 'Furnitures'),
    ('Home Deco', 'Home Deco'),
    ('Dressings', 'Dressings'),
    ('Tables', 'Tables'),
]

prod_col=[
    ('Red', 'Red'),
    ('Blue', 'Blue'),
    ('Green', 'Green'),
    ('Yellow', 'Yellow'),
    ('Black', 'Black'),
    ('White', 'White'),
    ('Brown', 'Brown'),
    ('Grey', 'Grey'),
]

class Product(models.Model):
    product_category= models.CharField(max_length=100, choices=prod_cat)
    product_brand=models.CharField(max_length=100, choices=prod_brand)
    product_name=models.CharField(max_length=100)
    product_description=models.TextField(max_length=500)
    product_color= models.CharField(max_length=100, choices=prod_col)
    product_price= models.IntegerField(validators=[
            MinValueValidator(1),
            MaxValueValidator(10000000),
        ])
    product_instock=models.BooleanField(default=True)
    product_date=models.DateTimeField(auto_now_add=True)
    product_image= ResizedImageField(quality= 85,upload_to='products_image/%y/%m/%d/')
    
    class Meta:
        verbose_name = 'Products'
        ordering = ['-product_date']
    
    def __str__(self):
        return self.product_name
    

class ProductImage(models.Model):
    product_images= models.ForeignKey(
        'Product',
        on_delete=models.CASCADE,
        related_name='product_images',
    )
    product_uploaded_image=ResizedImageField(quality= 85,upload_to='products_image/%y/%m/%d/images')
    product_image_date=models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name = 'Product Images'
        ordering = ['-product_image_date']
    
    def image_limiter(self):
        existing_images = ProductImage.objects.filter(product_images=self.product_images).count()
        if existing_images > 4:
            raise ValidationError("You can upload a maximum of 4 images per product.")
    
    def __str__(self):
        self.image_limiter()
        return self.product_image_date.strftime("%Y-%m-%d %H:%M:%S")

    
class Cart(models.Model):
        cart_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='cart_user')
        cart_product = models.ForeignKey(Product, on_delete=models.CASCADE)
        cart_quantity = models.PositiveIntegerField(default=1)
        cart_sub_price = models.DecimalField(max_digits=10, decimal_places=2)
        cart_delivery_fees = models.DecimalField(max_digits=10, decimal_places=2)
        cart_total_price = models.DecimalField(max_digits=10, decimal_places=2)

        class Meta:
            verbose_name = 'Cart'
            ordering = ['cart_user']
            
        
        def __str__(self):
            return f"{self.cart_quantity} of {self.cart_product.product_name} for {self.cart_user.first_name} {self.cart_user.last_name}"

class Subscribtions(models.Model):
    subscribtion_user= models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    subscribtions_email= models.EmailField()
    subscribtion_date= models.DateTimeField(auto_now_add=True)

products/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.db.models import Min
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from .models import Product, ProductImage, Cart, Subscribtions
from .filters import ProductFilter
from django.contrib.auth import logout
from django.core.mail import send_mail
from django.conf import settings

# Create your views here.
@csrf_exempt
@login_required
def home(request):
    cart_items= Cart.objects.filter(cart_user= request.user)
    # getting each item least price
    def least_price(product='none'):
        leastprice = Product.objects.filter(product_instock=True, product_category=product).aggregate(Min('product_price'))
        return leastprice
    
    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('users:login')
    
    
    # Isn't allowed on Railway
    
#     if request.method == 'POST' and 'email_subscription' in request.POST:
#         email= request.POST.get('email_subscription')
#         Subscribtions.objects.create(
#             subscribtion_user= request.user,
#             subscribtions_email= email,
#         )
        
#         message=f"""Hi {request.user.first_name},

# Subscription confirmed — welcome to the community!
#         """
#         send_mail(
#             "Furniture Payment",
#             message,
#             settings.EMAIL_HOST_USER,
#             [request.user.email],
#             fail_silently=False,
#         )
    
    context={
        'chairs': least_price('Chairs'),
        'home_deco': least_price('Home Deco'),
        'tables': least_price('Tables'),
        'cart_items': cart_items,
    }
    return render(request, 'products/home.html', context)

@login_required
@csrf_exempt
@cache_page(60 * 15, key_prefix='shop_page') 
def shop(request):
    # Queryset of products
    products= Product.objects.filter(product_instock=True)
    
    cart_items= Cart.objects.filter(cart_user= request.user)
    
    if 'select_order' in request.GET:
        per_page = request.GET.get('select_order')
        if per_page == 'date':
            products= products.order_by('product_date')
        elif per_page == 'newest':
            products= products.order_by('-product_date')
        elif per_page == 'popular':
            products= products.order_by('-product_price')
            
    if 'add_to_cart_btn' in request.POST:
        product_id = request.POST.get('add_to_cart_btn')
        product = Product.objects.get(id=product_id)
        cart_item, created = Cart.objects.get_or_create(
        cart_user=request.user,
        cart_product=product,
        defaults={
            "cart_quantity": 1,
            "cart_sub_price": product.product_price,
            "cart_delivery_fees": 50,
            "cart_total_price": product.product_price + 50,
        },
        )
        cart_item.save()
        
        if not created:
                cart_item.cart_quantity += 1
                cart_item.cart_sub_price = product.product_price * cart_item.cart_quantity
                cart_item.cart_total_price = cart_item.cart_sub_price + cart_item.cart_delivery_fees
                cart_item.save()

                return redirect('products:cart')
        
    
    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('users:login')
    
    # Isn't allowed on Railway
    
#     if request.method == 'POST' and 'email_subscription' in request.POST:
#         email= request.POST.get('email_subscription')
#         Subscribtions.objects.create(
#             subscribtion_user= request.user,
#             subscribtions_email= email,
#         )
        
#         message=f"""Hi {request.user.first_name},

# Subscription confirmed — welcome to the community!
#         """
#         send_mail(
#             "Furniture Payment",
#             message,
#             settings.EMAIL_HOST_USER,
#             [request.user.email],
#             fail_silently=False,
#         )
    
    # Apply filters
    myfilter= ProductFilter(request.GET, queryset=products)
    products= myfilter.qs
    
    # Pagination
    products_per_page = request.GET.get('select_product_number')
    per_page = int(products_per_page) if products_per_page else 8
    paginator = Paginator(products, per_page)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    
    context={
        'products': page_obj,
        'myfilter': myfilter,
        'cart_items': cart_items,
    }
    return render(request, 'products/shop.html', context)

@login_required
@csrf_exempt
def product_details(request, pk):
    # Get the product by its primary key
    product= Product.objects.get(id=pk)
    product_images= ProductImage.objects.filter(product_images=product)
    
    cart_items= Cart.objects.filter(cart_user= request.user)
    
    # Add to cart functionality
    if request.method == 'POST':
        add_to_cart = request.POST.get('addtocart')
        if add_to_cart:
            quantity = int(request.POST.get('quantity', 1))
            cart_item, created = Cart.objects.get_or_create(
                cart_user=request.user,
                cart_product=product,
                defaults={
                    "cart_quantity": quantity,
                    "cart_sub_price": product.product_price * quantity,
                    "cart_delivery_fees": 50,
                    "cart_total_price": (product.product_price * quantity) + 50,
                }
            )
            
            if not created:
                cart_item.cart_quantity = quantity
                cart_item.cart_sub_price = product.product_price * cart_item.cart_quantity
                cart_item.cart_total_price = cart_item.cart_sub_price + cart_item.cart_delivery_fees
                cart_item.save()

            cart_item.save()
            
            
    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('users:login')
    
    
    # Isn't allowed on Railway
    
#     if request.method == 'POST' and 'email_subscription' in request.POST:
#         email= request.POST.get('email_subscription')
#         Subscribtions.objects.create(
#             subscribtion_user= request.user,
#             subscribtions_email= email,
#         )
        
#         message=f"""Hi {request.user.first_name},

# Subscription confirmed — welcome to the community!
#         """
#         send_mail(
#             "Furniture Payment",
#             message,
#             settings.EMAIL_HOST_USER,
#             [request.user.email],
#             fail_silently=False,
#         )
    
    
    context={
        'product': product,
        'product_images': product_images,
        'cart_items': cart_items,
    }
    return render(request, 'products/product-details.html', context)


@login_required
@csrf_exempt
def cart(request):
    # Get cart items for the logged-in user
    cart_items= Cart.objects.filter(cart_user= request.user)
    
    # Calculate subtotal and total prices
    sub_prices = 0
    total_prices = 0
    for item in cart_items:
        sub_prices+= item.cart_sub_price
        total_prices+= item.cart_total_price
    
    if request.method == "POST":
        
        item_id = request.POST.get("item_id")

        if item_id:
                item = Cart.objects.get(id=item_id, cart_user=request.user)

                if item:
                    quantity = int(request.POST.get("cart_quantity", 1))

                    if quantity < 1:
                        quantity = 1

                    item.cart_quantity = quantity
                    item.cart_sub_price = item.cart_product.product_price * quantity
                    item.cart_total_price = item.cart_sub_price + item.cart_delivery_fees
                    item.save()
        
    
    if request.method == 'POST' and 'logout' in request.POST:
        logout(request)
        return redirect('users:login')
    
    
    # Isn't allowed on Railway
    
#     if request.method == 'POST' and 'email_subscription' in request.POST:
#         email= request.POST.get('email_subscription')
#         Subscribtions.objects.create(
#             subscribtion_user= request.user,
#             subscribtions_email= email,
#         )
        
#         message=f"""Hi {request.user.first_name},

# Subscription confirmed — welcome to the community!
#         """
#         send_mail(
#             "Furniture Payment",
#             message,
#             settings.EMAIL_HOST_USER,
#             [request.user.email],
#             fail_silently=False,
#         )
    
    context={
        'cart_items': cart_items,
        'sub_prices': sub_prices,
        'total_prices': total_prices,
    }
    return render(request, 'products/cart.html', context)

products/templates/products/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo" style="margin-bottom: 80px !important;">
                <a href="{% url 'products:home' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
            </div>

            <div class="user-greeting d-flex align-items-center gap-2" style="font-size:14px; color: #fbb710; margin-bottom: 20px;">
            <span>Hi, {{ request.user.first_name }}!</span>
            <form method="POST" action="" style="margin-left: auto;">
                {% csrf_token %}
                <button type="submit" class="btn-logout-icon" name="logout" style="
                background:none;
                border:none;
                color:#fbb710;
                font-size:16px;
                cursor:pointer;
                transition:0.3s;
            " title="Logout">
                <i class="fa fa-sign-out" aria-hidden="true"></i>
            </button>
            </form>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li><a href="{% url 'products:home' %}">Home</a></li>
                    <li><a href="{% url 'products:shop' %}">Shop</a></li>
                    <li class="active"><a href="{% url 'products:cart' %}">Cart</a></li>
                    <li><a href="{% url 'payment:checkout' %}">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">

            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="{% url 'products:cart' %}" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> Cart <span>({{ cart_items.count|default:0 }})</span></a>            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->

        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="cart-title mt-50">
                            <h2>Shopping Cart</h2>
                        </div>

                        <div class="cart-table clearfix">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for item in cart_items %}
                                    <tr>
                                        <td class="cart_product_img">
                                            <a href="#"><img src="{{item.cart_product.product_image.url}}" alt="Product"></a>
                                        </td>
                                        <td class="cart_product_desc">
                                            <h5>{{item.cart_product.product_name}}</h5>
                                        </td>
                                        <td class="price">
                                            <span>${{item.cart_product.product_price}}</span>
                                        </td>
                                        <td class="qty">
                                            <form method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="item_id" value="{{ item.id }}">
                                            <div class="qty-btn d-flex">
                                                <p>Qty</p>
                                                <div class="quantity">
                                                    <span class="qty-minus"  onclick="var effect = document.getElementById('{{ item.id }}');
                                                    var qty = parseInt(effect.value);
                                                    if (!isNaN(qty) && qty > 1) effect.value--;
                                                    effect.form.submit();
                                                    return false;"><i class="fa fa-minus" aria-hidden="true"></i></span>
                                                    
                                                    <input type="number" class="qty-text" id="{{ item.id }}" step="1" min="1" max="300" name="cart_quantity" value="{{ item.cart_quantity }}" onchange="this.form.submit()">
                                                    <span class="qty-plus" onclick="var effect = document.getElementById('{{ item.id }}');
                                                    var qty = effect.value;
                                                    if (!isNaN(qty)) effect.value++;
                                                    effect.form.submit();
                                                    return false;"><i class="fa fa-plus" aria-hidden="true"></i></span>
                                                </div>
                                            </div>
                                            </form>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Cart Total</h5>
                            <ul class="summary-table">
                                <li><span>subtotal:</span> <span>${{sub_prices}}</span></li>
                                <li><span>delivery:</span> <span>$50</span></li>
                                <li><span>total:</span> <span>${{total_prices}}</span></li>
                            </ul>
                            <div class="cart-btn mt-100">
                                <a href="{% url 'payment:checkout' %}" class="btn amado-btn w-100">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->
{% endblock %}

products/templates/products/product-details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo" style="margin-bottom: 80px !important;">
                <a href="{% url 'products:home' %}"><img src="{% static 'img/core-img/logo.png' %}" alt=""></a>
            </div>

            <div class="user-greeting d-flex align-items-center gap-2" style="font-size:14px; color: #fbb710; margin-bottom: 20px;">
            <span>Hi, {{ request.user.first_name }}!</span>
            <form method="POST" action="" style="margin-left: auto;">
                {% csrf_token %}
                <button type="submit" class="btn-logout-icon" name="logout" style="
                background:none;
                border:none;
                color:#fbb710;
                font-size:16px;
                cursor:pointer;
                transition:0.3s;
            " title="Logout">
                <i class="fa fa-sign-out" aria-hidden="true"></i>
            </button>
            </form>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li><a href="{% url 'products:home' %}">Home</a></li>
                    <li><a href="{% url 'products:shop' %}">Shop</a></li>
                    <li class="active"><a href="{% url 'products:product-details' product.id %}">Product</a></li>
                    <li><a href="{% url 'products:cart' %}">Cart</a></li>
                    <li><a href="{% url 'payment:checkout' %}">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="{% url 'products:cart' %}" class="cart-nav"><img src="{% static 'img/core-img/cart.png' %}" alt=""> Cart <span>({{ cart_items.count|default:0 }})</span></a>
                <a href="#" class="search-nav"><img src="{% static 'img/core-img/search.png' %}" alt=""> Search</a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->

        <!-- Product Details Area Start -->
        <div class="single-product-area section-padding-100 clearfix">
            <div class="container-fluid">

                <div class="row">
                    <div class="col-12">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb mt-50">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item"><a href="#">Furniture</a></li>
                                <li class="breadcrumb-item"><a href="#">Chairs</a></li>
                                <li class="breadcrumb-item active" aria-current="page">white modern chair</li>
                            </ol>
                        </nav>
                    </div>
                </div>

                <div class="row">
                    <div class="col-12 col-lg-7">
                        <div class="single_product_thumb">
                            <div id="product_details_slider" class="carousel slide" data-ride="carousel">
                                <ol class="carousel-indicators">
                                    <li class="active" data-target="#product_details_slider" data-slide-to="0" style="background-image: url({{ product.product_image.url }});">
                                    </li>
                                    {% for image in product_images %}
                                    <li data-target="#product_details_slider" data-slide-to="{{ forloop.counter }}" style="background-image: url({{ image.product_uploaded_image.url }});">
                                    </li>
                                    {% endfor %}
                                </ol>
                                <div class="carousel-inner">
                                    <div class="carousel-item active">
                                        <a class="gallery_img" href="{{ product.product_image.url }}">
                                            <img class="d-block w-100" src="{{ product.product_image.url }}" alt="First slide">
                                        </a>
                                    </div>
                                    {% with product.product_images.all as images %}
                                    {% if product.product_images.count >= 1 %}
                                    <div class="carousel-item">
                                        <a class="gallery_img" href="{{ images.0.product_uploaded_image.url }}">
                                            <img class="d-block w-100" src="{{ images.0.product_uploaded_image.url }}" alt="Second slide">
                                        </a>
                                    </div>
                                    {% elif product.product_images.count >= 2 %}
                                    <div class="carousel-item">
                                        <a class="gallery_img" href="{{ images.1.product_uploaded_image.url }}">
                                            <img class="d-block w-100" src="{{ images.1.product_uploaded_image.url }}" alt="Third slide">
                                        </a>
                                    </div>
                                    {% elif product.product_images.count >= 3 %}
                                    <div class="carousel-item">
                                        <a class="gallery_img" href="{{ images.2.product_uploaded_image.url }}">
                                            <img class="d-block w-100" src="{{ images.2.product_uploaded_image.url }}" alt="Fourth slide">
                                        </a>
                                    </div>
                                    {% endif %}
                                    {% endwith %}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-12 col-lg-5">
                        <div class="single_product_desc">
                            <!-- Product Meta Data -->
                            <div class="product-meta-data">
                                <div class="line"></div>
                                <p class="product-price">${{product.product_price}}</p>
                                <a href="product-details.html">
                                    <h6>{{product.product_name}}</h6>
                                </a>
                                <!-- Ratings & Review -->
                                <div class="ratings-review mb-15 d-flex align-items-center justify-content-between">
                                    <div class="ratings">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </div>
                                </div>
                                <!-- Avaiable -->
                                {% if product.product_instock %}
                                <p class="avaibility"><i class="fa fa-circle"></i> In Stock</p>
                                {% else %}
                                <p class="avaibility"><i class="fa fa-circle"></i> Out of Stock</p>
                                {% endif %}
                            </div>

                            <div class="short_overview my-5">
                                <p>{{product.product_description}}</p>
                            </div>

                            <!-- Add to Cart Form -->
                                <form class="cart clearfix" method="post">
                                    {% csrf_token %}
                                    <div class="cart-btn d-flex mb-50">
                                        <p>Qty</p>
                                        <div class="quantity">
                                            <span class="qty-minus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty ) &amp;&amp; qty &gt; 1 ) effect.value--;return false;"><i class="fa fa-caret-down" aria-hidden="true"></i></span>
                                            <input type="number" class="qty-text" id="qty" step="1" min="1" max="300" name="quantity" value="1">
                                            <span class="qty-plus" onclick="var effect = document.getElementById('qty'); var qty = effect.value; if( !isNaN( qty )) effect.value++;return false;"><i class="fa fa-caret-up" aria-hidden="true"></i></span>
                                        </div>
                                    </div>
                                    <button type="submit" name="addtocart" value="5" class="btn amado-btn">Add to cart</button>
                                </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Product Details Area End -->
    </div>
{% endblock %}